name: Rust

on: ["push", "pull_request"]

concurrency:
  group: rust-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # @v3.1.0

      - name: cargo fmt
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # @v1.0.1
        with:
          command: fmt
          args: --all -- --check

  cargo-clippy:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
          - windows-2022

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # @v3.1.0

      - name: cargo clippy
        uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d # @v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --locked --all-targets -- -D warnings

  cargo-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # @v3.1.0

      - name: Check Documentation
        run: cargo doc --locked --all --no-deps --lib

  cargo-test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
          - windows-2022

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # @v3.1.0

      - name: cargo test --locked
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # @v1.0.1
        with:
          command: test
